### ISSUE TITLE
Design Toolbox

### ISSUE THREAD

**Issue by gbaudusseau** [w3c/developer-tools#18]
I decided to open this issue to discuss about the design and the architecture of the [toolbox](http://w3c.github.io/developer-tools/#tools). (first section in the developer tools webpage).

Currently, the tools are displaying with an index. The fact is our number of tools is limited and this index is maybe, useless. 

So, I am asking what could be the best way to order and display our tools in this toolbox?

**Comment by gbaudusseau** [comment]
Examples, ideas are welcome! :)

**Comment by tripu** [comment]
I think you're right in that indexing by first letter may be too much, given the (low) number of entries.

Why not a simple vertical list, with one line per tool?
- **[CSS Validator](https://jigsaw.w3.org/css-validator/)** _Helps Web designers and Web developers check Cascading Style Sheets (CSS)_
- **[Internationalization Checker](http://validator.w3.org/i18n-checker/)** _Performs tests to determine level of internationalisation-friendliness_
- [etc]

If you want something fancier, maybe one of those mosaics, with one coloured square tile per tool? The problem with those is that the order isn't obvious at first sight (is it vertical, or horizontal?). I find them less usable/accessible. It'll also take more real estate, and maybe the descriptions won't fit in the tiles.

**Comment by gbaudusseau** [comment]
I thought about the list but I think it will be annoying for people to find the tool they are looking for even if there is not a lot.
I thought about create categories like https://developer.mozilla.org/en-US/docs/Tools (scroll down to see).

for example it could be:
- Mobile
- Debugging
- APIs and Libraries
- ...

**Comment by tripu** [comment]
Those categories look good. I'd say anything that doesn't force you to have exactly 26 sections, where some of them are going to be empty while others contain several items. But no big deal.

**Comment by astorije** [comment]
Categories seem like a good idea indeed, but you'll see that categorizing will not be always trivial. For example, if people providing the tools also request in what category they want to appear in, you'll end up having one tool per category (Internationalization Checker in "Internationalization", Mobile Checker in "Mobile", ...), killing the point of categories in the first place.
I could see that happening for [specification groups](http://www.w3.org/TR/). There are so many of them now that it became pointless and we are even leaning towards removing them.

All in all, my opinion is that this gets over-engineered. You were taking the npm repository as an example (136k packages) when designing your search bar. I also see that Mozilla has about 40 tools, which is a good number to start categorizing them. Here, we have 10 tools, some of them being partially redundant (Markup Validator and Validator.nu, MobileOK Checker and Mobile Checker, Unicorn being orthogonal to HTML + CSS checkers).
In the end, I liked your first idea: a "grid" of tools 3x4, or 4x3 (or whatever) with a short description. My understanding is that that is what @tripu suggests, more or less (minus the colored square, because that depends on the rest of your design). @tripu, I don't think the order matters here, which is at the grid's advantage actually.

So my 2 cents here, in summary, are: keep it simple. You have more or less 7 actual tools (counting only the "different" ones in terms of goals), which is a good number to not care of how you present them. Present them in a way that people will read them all, and you don't have to care about categories.

**Comment by gbaudusseau** [comment]
I notice that categorizing our tools is not trivial yes. I set up a classic display instead. Let's see in the future if we can find a fancier way to display it.
